version: '3'
services:
  csv_ingestion:
    build: .
    volumes:
      - ./data:/app/data
      - ./scripts:/app/scripts
      - ./key.json:/app/key.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/your_key.json
      - PROJECT_ID=your-project-id
      - DATASET_ID=your-dataset